In [1]:
import numpy as np
from sklearn import datasets
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [14]:
iris = datasets.load_digits()
X = iris.data
Y = iris.target
print(X)
print(Y)
print(X.shape)
print(Y.shape)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]
(1797, 64)
(1797,)


In [18]:
X_embedded = LinearDiscriminantAnalysis(n_components=30).fit(X,Y).transform(X)

/home/akshay/.local/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:466: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(64, 10 - 1) = 9 components.
  ChangedBehaviorWarning)
/home/akshay/.local/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:472: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)
/home/akshay/.local/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [17]:
print(X_embedded.shape)

(1797, 9)


In [8]:
LinearDiscriminantAnalysis(n_components=2).explained_variance_ratio_

AttributeError: 'LinearDiscriminantAnalysis' object has no attribute 'explained_variance_ratio_'